# PocketSDR options for L1CA GRAPHIC PPP

el_mask = 40 # for outdoor test around Birch

# L1CA parameters (at or near defaults)
thres_cn0_l = 34.0   # L1CA acquisition CN0 threshold dB-Hz (default)
thres_cn0_u = 30.0   # L1CA loss-of-lock CN0 threshold dB-Hz (default)

# Loop filter bandwidths (applied to all signals)
b_pll       = 3.0    # PLL bandwidth Hz (default 5.0)
b_fll_n     = 1.0    # steady-state FLL bandwidth Hz (default 2.0)
